### ISSUE TITLE
ERROR: Source files failed integrity check!

### ISSUE THREAD

**Issue by yura121** [bbrks/aur-portainer-bin#4]
> Сборка portainer-bin...
> ==> Сборка пакета portainer-bin 2.11.1-1 (Чт 10 фев 2022 14:31:04)
> ==> Проверка зависимостей для запуска...
> ==> Проверка зависимостей для сборки...
> ==> Получение исходных файлов...
>   -> Найден portainer.service
>   -> Найден portainer.png
>   -> Найден portainer.desktop
>   -> Найден portainer-2.11.1-src.tar.gz
>   -> Найден portainer-2.11.1-linux-amd64.tar.gz
> ==> Проверка файлов source с использованием sha256sums...
>     portainer.service ... Готово
>     portainer.png ... Готово
>     portainer.desktop ... Готово
>     portainer-2.11.1-src.tar.gz ... СБОЙ
> ==> ОШИБКА: Исходные файлы не прошли проверку целостности!
>

**Comment by bbrks** [comment]
Thanks. Looks like they pushed a new release for 2.11.1 without bumping version number 🤷
